services:
  db:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db_user
      - MONGO_INITDB_ROOT_PASSWORD=grY3ANahkuXxUqRT8nztVHKDsjEL7cb2JB4MyepP
    networks:
      - eventshuffle-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app # Hot reload
    command: npm run dev
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_USER=db_user
      - DB_HOST=db
      - DB=db
      - DB_PASSWORD=grY3ANahkuXxUqRT8nztVHKDsjEL7cb2JB4MyepP
      - DB_PORT=27017
      - ENVIRONMENT=dev
      - PORT=3000
    networks:
      - eventshuffle-network

networks:
  eventshuffle-network:
    driver: bridge
