services:
  db:
    image: postgres:17.2
    restart: unless-stopped
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=grY3ANahkuXxUqRT8nztVHKDsjEL7cb2JB4MyepP
    networks:
      - eventshuffle-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app # Hot reload
    command: npm run dev
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_USER=db_user
      - DB_HOST=db
      - DB=db
      - DB_PASSWORD=grY3ANahkuXxUqRT8nztVHKDsjEL7cb2JB4MyepP
      - DB_PORT=5432
      - ENVIRONMENT=dev
      - PORT=3000
    networks:
      - eventshuffle-network

networks:
  eventshuffle-network:
    driver: bridge
