services:
  db:
    image: mongo:8.0
    restart: unless-stopped
    volumes:
      - ./db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db_user
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - eventshuffle-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_USER=db_user
      - DB_HOST=db
      - DB=db
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=27017
      - ENVIRONMENT=prod
      - PORT=3000
    networks:
      - eventshuffle-network

networks:
  eventshuffle-network:
    driver: bridge
